changelog:
  categories:
    - title: Breaking changes 🚨
      labels:
        - breaking changes
    - title: New features 🎉
      labels:
        - enhancement
    - title: Performance related 📈
      labels:
        - performance
    - title: Fixes 🛠️
      labels:
        - bug
    - title: Dependencies 🗃️
      labels:
        - dependencies
    - title: Other
      labels:
        - "*"