name: deploy-tag

on:
  push:
    tags:
      - '*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: ${{ vars.JAVA_VENDOR }}
          java-version: ${{ vars.JAVA_VERSION }}

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper

      - name: Gradle build
        run: ./gradlew build testClasses -x check

      - name: Gradle check
        run: ./gradlew check

      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: |
            build/libs
            build/reports

      - name: Gradle publish to Reposilite
        run: |
          ./gradlew publishLocalPublicationToReposiliteRepository \
          -PreposiliteSnapshots=${{ secrets.REPOSILITE_SNAPSHOTS }} \
          -PreposiliteUsername=${{ secrets.REPOSILITE_USERNAME }} \
          -PreposilitePassword=${{ secrets.REPOSILITE_PASSWORD }} \