name: update-test-suite

on:
  pull_request:
  workflow_dispatch:

jobs:
  fetch-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout test suite
        uses: actions/checkout@v4
        with:
          repository: json-schema-org/JSON-Schema-Test-Suite
          path: test-suite
          sparse-checkout: |
            remotes
            tests/draft2019-09
            tests/draft2020-12
      - name: Checkout json-schema
        uses: actions/checkout@v4
        with:
          path: json-schema
      - run: |
          cd test-suite
          tree